### ISSUE TITLE
"!check_token" Doesn't work after a while. + Chat history seems to fail if any media file is uploaded and it's been 2 days after the upload time. 

### ISSUE THREAD

**Issue by War004** [War004/Google-gemini-discord-bot#1]
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "<ipython-input-10-f57a04efe76e>", line 68, in on_message
    response = f"{model.count_tokens(chat.history)}"
  File "/usr/local/lib/python3.10/dist-packages/google/generativeai/generative_models.py", line 348, in count_tokens
    return self._client.count_tokens(request, **request_options)
  File "/usr/local/lib/python3.10/dist-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 1474, in count_tokens
    response = rpc(
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/rest.py", line 543, in __call__
    raise core_exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:countTokens?%24alt=json%3Benum-encoding%3Dint: You do not have permission to access the File v3xvw7tabsgg or it may not exist.

Temporary fixed would be renaming your chat log file, but it will reset the chat history. Will try to reproduced the problem and see more in detail. 

Seems to happen after the files gets deleted stored in the files api

**Comment by War004** [comment]
You can remove the text block like in the given example below
Before:
![image](https://github.com/War004/Google-gemini-discord-bot/assets/138228378/639d8d40-f156-4adb-9c23-61a6f146a211)
After: 
![image](https://github.com/War004/Google-gemini-discord-bot/assets/138228378/3d0c4c8e-5c09-4719-94e0-b40fe8ff1128)

I am having my final exam staring from 7th June so, I need to give my time towards them, till 18th june.
